"""add optimization_objectives and known_issues

Revision ID: 57e916d2e041
Revises: 84e609cd980b
Create Date: 2026-05-18 11:44:05.018200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e916d2e041'
down_revision: Union[str, Sequence[str], None] = '84e609cd980b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('known_issues', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('optimization_objectives', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_column('optimization_objectives')
        batch_op.drop_column('known_issues')

    # ### end Alembic commands ###
